config/routes.rb
Rails.application.routes.draw do
  get 'page/index'
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :cours
  resources :formations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "page#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cour.rb
class Cour < ApplicationRecord
  belongs_to :formation
  has_one_attached :video
  has_one_attached :thumbnail

  validates_presence_of :video, :thumbnail, :title, :descriptin, :formation_id
end

app/models/formation.rb
class Formation < ApplicationRecord
  has_many :cours
end

app/models/guest_user.rb
class GuestUser < User
	attr_accessor :name, :first_name, :last_name, :email, :id, :role
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :editor], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #include DeviseWhitelist
	include SetSource
	include CurrentUserConcern
	#include DefaultPageContent
end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
	extend ActiveSupport::Concern

	def current_user
		super || guest_user
	end

	def guest_user
		guest = GuestUser.new
		guest.name = "Guest User"
		guest.first_name = "Guest"
		guest.last_name = "User"
		guest.email = "guest@example.user"
		guest.role = "guest_user"
		guest
	end
end

app/controllers/concerns/default_page_content.rb
module DefaultPageContent
	extend ActiveSupport::Concern

	included do
		before_action :set_page_defaults
	end

	def set_page_defaults
		@page_title = "CLINIQUE | KHADJIJA"
		@seo_keywords = "CLINIQUE KHADIJA VOTRE SANTÉ, NOTRE FIERTÉ"
	end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
	extend ActiveSupport::Concern

	included do
		before_action :configure_permitted_parameters, if: :devise_controller?
	end

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
		devise_parameter_sanitizer.permit(:account_update, keys: [:name])
	end
end

app/controllers/concerns/set_source.rb
module SetSource
	extend ActiveSupport::Concern

	included do
		before_action :set_source
	end

	def set_source
		session[:source] = params[:q] if params[:q] 	
	end
end

app/controllers/cours_controller.rb
class CoursController < ApplicationController
  before_action :set_cour, only: %i[ show edit update destroy ]

  access [:all, :user] => [:index, :show, {except: [:destroy, :edit, :update, :new, :create]}], editor: [:index, :show, :edit, :update, :new, :create, :destroy], admin: :all
  # GET /cours or /cours.json
  def index
    @cours = Cour.all
  end

  # GET /cours/1 or /cours/1.json
  def show
  end

  # GET /cours/new
  def new
    @cour = Cour.new
  end

  # GET /cours/1/edit
  def edit
  end

  # POST /cours or /cours.json
  def create
    @cour = Cour.new(cour_params)

    respond_to do |format|
      if @cour.save
        format.html { redirect_to @cour, notice: "Cour was successfully created." }
        format.json { render :show, status: :created, location: @cour }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cours/1 or /cours/1.json
  def update
    respond_to do |format|
      if @cour.update(cour_params)
        format.html { redirect_to @cour, notice: "Cour was successfully updated." }
        format.json { render :show, status: :ok, location: @cour }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cours/1 or /cours/1.json
  def destroy
    @cour.destroy
    respond_to do |format|
      format.html { redirect_to cours_url, notice: "Cour was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cour
      @cour = Cour.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cour_params
      params.require(:cour).permit(:title, :descriptin, :thumbnail, :video, :formation_id)
    end
end

app/controllers/formations_controller.rb
class FormationsController < ApplicationController
  before_action :set_formation, only: %i[ show edit update destroy ]

  # GET /formations or /formations.json
  def index
    @formations = Formation.all
  end

  # GET /formations/1 or /formations/1.json
  def show
  end

  # GET /formations/new
  def new
    @formation = Formation.new
  end

  # GET /formations/1/edit
  def edit
  end

  # POST /formations or /formations.json
  def create
    @formation = Formation.new(formation_params)

    respond_to do |format|
      if @formation.save
        format.html { redirect_to @formation, notice: "Formation was successfully created." }
        format.json { render :show, status: :created, location: @formation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @formation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formations/1 or /formations/1.json
  def update
    respond_to do |format|
      if @formation.update(formation_params)
        format.html { redirect_to @formation, notice: "Formation was successfully updated." }
        format.json { render :show, status: :ok, location: @formation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @formation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formations/1 or /formations/1.json
  def destroy
    @formation.destroy
    respond_to do |format|
      format.html { redirect_to formations_url, notice: "Formation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_formation
      @formation = Formation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def formation_params
      params.require(:formation).permit(:name)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cours_helper.rb
module CoursHelper
end

app/helpers/formations_helper.rb
module FormationsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/cours/_form.html.erb
<%= form_with(model: cour, local: true) do |form| %>
  <% if cour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cour.errors.count, "error") %> prohibited this cour from being saved:</h2>

      <ul>
      <% cour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :formation_id %>
    <%= form.collection_select(:formation_id, Formation.all, :id, :name,
        {
          include_blank: true
        },
        class: 'form-control',
      ) 
    %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :descriptin %>
    <%= form.text_area :descriptin %>
  </div>

  <div class="field">
    <%= form.label :video %>
    <%= form.file_field :video %>
  </div>

  <div class="field">
    <%= form.label :thumbnail %>
    <%= form.file_field :thumbnail %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cours/edit.html.erb
<h1>Editing Cour</h1>

<%= render 'form', cour: @cour %>

<%= link_to 'Show', @cour %> |
<%= link_to 'Back', cours_path %>

app/views/cours/index.html.erb
<div style="">
<p id="notice"><%= notice %></p>

<!--h1>Cours</h1-->
<%= current_user.role %>
  <div style="display:flex;justify-content:center;">

    <% @cours.each do |cour| %>

      <div class="card col-sm-3" style="margin-right: 2rem;">
        <span class="card-img-top"><%= image_tag url_for(cour.thumbnail), class:"card-img-top"%></span>
        <%#= image_tag "SamplePNGImage_30mbmb", class:"card-img-top", alt:"Card image cap" %>
        <!-- img class="card-img-top" src="..." alt="Card image cap" -->
        <div class="card-body">
          <h5 class="card-title"><%= cour.title %></h5>
          <p class="card-text"><%= cour.descriptin %>. Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <%= link_to 'Show', cour, class:"btn btn-primary", style:"background-color:#023047;" %>
          <%= link_to 'Edit', edit_cour_path(cour), class:"btn btn-primary", style:"background-color:#023047;"  if logged_in?(:admin, :editor) %>
          <%= link_to 'Destroy', cour, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"  if logged_in?(:admin, :editor) %>
          <!--a href="#" class="btn btn-primary"  style="background-color:#023047;">Go somewhere</a -->
        </div>
      </div>
    <% end %>
  </div>
  
<br>

<%= link_to 'New Cour', new_cour_path %>

</div>

app/views/cours/new.html.erb
<h1>New Cour</h1>

<%= render 'form', cour: @cour %>

<%= link_to 'Back', cours_path %>

app/views/cours/show.html.erb
<p id="notice"><%= notice %></p>
<link href="https://vjs.zencdn.net/7.14.3/video-js.css" rel="stylesheet" />

  <!-- If you'd like to support IE8 (for Video.js versions prior to v7) -->
  <!-- <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script> -->

<%= link_to 'Edit', edit_cour_path(@cour) if logged_in?(:admin, :editor) %> |
<%= link_to 'Back', cours_path %>
<p>
  <strong>Formation:</strong>
  <%= @cour.formation.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @cour.title %>
</p>

<p>
  <strong>Descriptin:</strong>
  <%= @cour.descriptin %>
</p>

<p style="width:800px;height:800px;">
<video
    id="my-video"
    class="video-js"
    controls
    preload="auto"
    width="100%"
    height="auto"
    poster="<%= url_for(@cour.thumbnail)%>"
    data-setup="{}"
  >
    <source src="<%= url_for(@cour.video) %>" type="video/mp4" />
  </video>
</p>

app/views/formations/_form.html.erb
<%= form_with(model: formation, local: true) do |form| %>
  <% if formation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(formation.errors.count, "error") %> prohibited this formation from being saved:</h2>

      <ul>
      <% formation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/formations/edit.html.erb
<h1>Editing Formation</h1>

<%= render 'form', formation: @formation %>

<%= link_to 'Show', @formation %> |
<%= link_to 'Back', formations_path %>

app/views/formations/index.html.erb
<!-- div class="row" style="padding: 0.25rem; margin-bottom: 4rem; margin-left: 4px; width:99.99%;" -->

  <div style="display:flex;justify-content:center;">
    
    <div class="card col-sm-3" style="margin-right: 2rem;">
      <%= image_tag "SamplePNGImage_30mbmb", class:"card-img-top", alt:"Card image cap" %>
      <!-- img class="card-img-top" src="..." alt="Card image cap" -->
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary"  style="background-color:#023047;">Go somewhere</a>
      </div>
    </div>

  </div>

<p id="notice"><%= notice %></p>
<%= link_to 'New Formation', new_formation_path %>

<h1>Formations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @formations.each do |formation| %>
      <tr>
        <td><%= formation.name %></td>
        <td><%= link_to 'Show', formation %></td>
        <td><%= link_to 'Edit', edit_formation_path(formation) %></td>
        <td><%= link_to 'Destroy', formation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/formations/new.html.erb
<h1>New Formation</h1>

<%= render 'form', formation: @formation %>

<%= link_to 'Back', formations_path %>

app/views/formations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @formation.name %>
</p>

<%= link_to 'Edit', edit_formation_path(@formation) %> |
<%= link_to 'Back', formations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwFormation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>

  </body>
</html>

app/views/layouts/page.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwFormation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/page/index.html.erb
<!-- span>border color border:4px solid #DFDFDF;</span -->
<!--div class="row" style="border:4px solid #DFDFDF; padding: 1rem; margin-bottom: 2rem; margin-left: 4px; width:99.99%;">

  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Special title treatment</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="#" class="btn btn-secondary">Go somewhere</a>
      </div>
    </div>
  </div>

  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Special title treatment</h5>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <a href="#" class="btn btn-primary">Go somewhere</a>
      </div>
    </div>
  </div>

</div-->

<div class="row" style="padding: 0.25rem; margin-bottom: 4rem; margin-left: 4px; width:99.99%;">

  <div style="display:flex;justify-content:center;">
    
    <div class="card col-sm-3" style="margin-right: 2rem;">
      <%= image_tag "SamplePNGImage_30mbmb", class:"card-img-top", alt:"Card image cap" %>
      <!-- img class="card-img-top" src="..." alt="Card image cap" -->
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary"  style="background-color:#023047;">Go somewhere</a>
      </div>
    </div>

    <div class="card col-sm-3" style="margin-right: 2rem;">
      <%= image_tag "SamplePNGImage_30mbmb", class:"card-img-top", alt:"Card image cap" %>
      <!-- img class="card-img-top" src="..." alt="Card image cap" -->
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary" style="background-color:#023047;" >Go somewhere</a>
      </div>
    </div>

    <div class="card col-sm-3" style="">
      <%= image_tag "SamplePNGImage_30mbmb", class:"card-img-top", alt:"Card image cap" %>
      <!-- img class="card-img-top" src="..." alt="Card image cap" -->
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary" style="background-color:#023047;" >Go somewhere</a>
      </div>
    </div>

  </div>
</div>


<!--div class="row" style="padding: 0.25rem; margin-bottom: 4px; margin-left: 4px; width:99.99%;">
    
    <div class="card mb-3" style="">
      <%= image_tag "SamplePNGImage_30mbmb", class:"card-img-top ", alt:"Card image cap" %>
      <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
    </div>

    <div class="card mb-3" style="width:45rem;">
      <%= image_tag "SamplePNGImage_30mbmb", class:"card-img-top ", alt:"Card image cap" %>
      <div class="card-body">
          <h5 class="card-title">Card title</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
    </div>

</div -->

app/views/shared/_footer.html.erb
<div class="footer footer-bg">

    <div class="footer-start">
        <div class="part">Logo</div>
        <div class="part">Message</div>
    </div>

    <div class="footer-center">
        <div class="part">Nos Formations
            <div class="">Formation 1</div>
            <div class="">Formation 2</div>
            <div class="">Formation 3</div>
        </div>

        <div class="part">Nos Cours
            <div class="">Cours 1</div>
            <div class="">Cours 2</div>
            <div class="">Cours 3</div>
        </div>

        <div class="part">Nos Services
            <div class="">Services 1</div>
            <div class="">Services 2</div>
            <div class="">Services 3</div>
        </div>

        <div class="part">Contact
            <div class="">Telephone: +36 1234567890</div>
            <div class="">Email: awformation@gmail.com</div>
            <div class="">Adresse: France Paris</div>
        </div>

    </div>

    <div class="footer-end">
        <div class="part">Nos Partenaires
            <div class="">Partenaire 1</div>
            <div class="">Partenaire 2</div>
            <div class="">Partenaire 3</div>
        </div>
    </div>
</div>

app/views/shared/_general_header.html.erb
<header class="p-3 bd_bottom_color text-dark">
    <a href="#" class="d-flex flex-wrap align-items-start justify-content-center justify-content-lg-start" style="font-family:cursive;font-size:2rem;margin-bottom: -1rem;width: 1rem;">J'existe</a>
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <!--a href="/" class="d-flex mb-2 mb-lg-0 text-dark text-decoration-none" style="font-family:cursive;">
        J'existe
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
      </a -->

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="#" class="nav-link px-2 text-dark">Home</a></li>
        <li><%= link_to "Hospital", hopitals_path(), class:'nav-link px-2 text-dark' %></li>
        <li><%= link_to "Medcins", medcins_path(), class:'nav-link px-2 text-dark' %></li>
        <li><%= link_to "Carnets de grossesses", patients_path(), class:'nav-link px-2 text-dark' %></li>
        
      </ul>

      <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
        <input type="search" class="form-control form-control-dark" placeholder="Recherche..." aria-label="Search">
      </form>

      <div class="text-end">
        <button type="button" class="btn btn-login me-2">Login</button>
        <button type="button" class="btn btn-danger">Deconnexion</button>
      </div>
    </div>
  </div>
</header>

app/views/shared/_header.html.erb
<header class="p-3 bd_bottom_hearder_color text-dark">
  <a href="#" class="d-flex flex-wrap align-items-start justify-content-center justify-content-lg-start" style="font-family:cursive;font-size:2rem;margin-bottom: -1rem;width: 1rem;">AW</a>
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <!--li><a href="#" class="nav-link px-2 text-dark">Home</a></li -->
        <li><%= link_to "Home", root_path(), class:'nav-link px-2 text-dark' %></li>
        <li><%= link_to "Formations", formations_path(), class:'nav-link px-2 text-dark' %></li>
        <li><%= link_to "Cours", cours_path(), class:'nav-link px-2 text-dark' %></li>
        <li><%= link_to "Autres", "#", class:'nav-link px-2 text-dark' %></li>
        
      </ul>

      <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
        <input type="search" class="form-control form-control-white" placeholder="Recherche..." aria-label="Search">
      </form>

      <div class="text-end">
      <%#= current_user.role == "guest_user" %>

      <% if current_user.role == "guest_user" %>
        <%= link_to "Se connecter", new_user_session_path(), class:'btn btn-login me-2' %>
        <%= link_to "S'inscrire", new_user_registration_path(), class:'btn btn-login me-2' %>
      <% else %>
        <%= link_to "Se deconnecter", destroy_user_session_path,method: :delete, class:'btn btn-danger' %>
      <% end %>
      </div>
    </div>
  </div>
</header>

app/views/shared/_header_copy.html.erb
<header class="p-3 bg-dark text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
        <li><%= link_to "Hospital", hopitals_path(), class:'nav-link px-2 text-white' %></li>
        <li><%= link_to "Medcins", medcins_path(), class:'nav-link px-2 text-white' %></li>
        <li><%= link_to "Carnets de grossesses", patients_path(), class:'nav-link px-2 text-white' %></li>
        
      </ul>

      <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
        <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
      </form>

      <div class="text-end">
        <button type="button" class="btn btn-outline-light me-2">Login</button>
        <button type="button" class="btn btn-warning">Sign-up</button>
      </div>
    </div>
  </div>
</header>

app/views/shared/_sidebar.html.erb
<div class="col-md-2" style="">
    <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-sidebar" style="height:35rem;">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
            <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
            <span class="fs-4">Sidebar</span>
        </a>
        <hr>
        <ul class="nav nav-pills flex-column mb-auto">
            <%= nav_helper 'li', 'nav-link', 'arrow-left','bi me-2', 'active'  %>
            <!--li>
                <a href="#" class="nav-link text-white">
                    <svg class="bi me-2" width="16" height="16"><use xlink:href="#speedometer2"/></svg> Dashboard
                </a>
            </!--li>
            <li>
                <a href="#" class="nav-link text-white">
                    <svg class="bi me-2" width="16" height="16"><use xlink:href="#table"/></svg> Orders
                </a>
            </li>
            <li>
                <a href="#" class="nav-link text-white">
                    <svg class="bi me-2" width="16" height="16"><use xlink:href="#grid"/></svg> Products
                </a>
            </li>
            <li>
                <a href="#" class="nav-link text-white">
                    <svg class="bi me-2" width="16" height="16"><use xlink:href="#people-circle"/></svg> Customers
                </a>
            </li -->
        </ul>
        <hr>
        <div class="dropdown">
            <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
                <strong>mdo</strong>
            </a>
            <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
                <li><a class="dropdown-item" href="#">New project...</a></li>
                <li><a class="dropdown-item" href="#">Settings</a></li>
                <li><a class="dropdown-item" href="#">Profile</a></li>
                <li>
                    <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="#">Sign out</a></li>
            </ul>
        </div>
    </div>
</div>